---
- name: add python package for adding new repository
  apt: name=python-software-properties state=present
  
- name: add new repository for nginx
  apt_repository: repo=ppa:nginx/stable state=present
  
- name: install nginx
  apt: name=nginx state=present
  
- name: apt upgrade
  apt: update_cache=yes force=yes
  
- name: ensure nginx start on boot
  service: name=nginx enabled=yes
  
- name: copy main nginx configuration file
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: restart nginx
  
- name: copy nginx logrotate script
  template: src=logrotate.d.nginx dest=/etc/logrotate.d/nginx